### ISSUE TITLE
Sistema de Redefinição de senha

### ISSUE THREAD

**Issue by klimber** [academiadev-jlle/backend-batatacombacon#68]
# Esquecimento de senha

Foram discutidas 2 formas de gerenciar o esquecimento de senhas

### O método

Esta é aparentemente uma forma mais simples de fazer, obviamente seria interessante que o usuário trocasse por uma senha própria o mais breve possível.

 1.  Usuário clica em **Esqueci minha senha** no site.
 2. É então levado para uma página onde deve colocar o email de cadastro da conta.
 3. Se o email estiver vinculado a uma conta, o usuário recebe um email com uma nova senha temporária gerada automaticamente.
 4. O usuário utiliza a nova senha para logar no site, e utiliza a ferramenta de troca de senha para cadastrar uma senha própria.

### Prós

- Implementação simplificada

### Contras

- Uma pessoa mal intecionada pode usar emails de outras contas para trocar as senhas e causar transtornos com trocas não solicitadas pelo dono da conta.

### O método

Forma utilizada pela grande maioria dos sites e serviços.

 1.  Usuário clica em **Esqueci minha senha** no site.
 2. É então levado para uma página onde deve colocar o email de cadastro da conta.
 3. Se o email estiver vinculado a uma conta, o usuário recebe um email com um token autorizando temporariamente o cadastro de uma nova senha. O usuário também é informado para ignorar o email se não solicitou a troca.
 4. Ao clicar no token, o usuário é direcionado para uma página onde pode cadastrar uma nova senha.

### Prós

- Impede o problema do método anterior

### Contras

- Aparentemente um pouco mais complexo de implementar

> Written with [StackEdit](https://stackedit.io/).

**Comment by eberjoe** [comment]
Pelo princípio do MVP a primeira opção é a mais apropriada para o projeto.
